// Generated by https://quicktype.io

export interface CatsImageResponse {
  tags:      string[];
  createdAt: string;
  updatedAt: string;
  validated: boolean;
  owner:     string;
  file:      string;
  mimetype:  string;
  size:      number;
  _id:       string;
  url:       string;
}
